version: '2'
services:
  web:
    image: odoo
    container_name: some_odoo
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=changeit
  mydb:
    image: postgres:9.4
    container_name: some_postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=changeit